fragment AssetPageIP on IP {
  _id
  address
  status
  tag
  subnets {
    range
  }
  nodes {
    host {
      network_services {
        service
        port
        protocol
      }
    }
  }
}

fragment AssetPageNetworkService on NetworkService {
  _id
  service
  protocol
  port
  hostsConnection(where: $hostWhere) {
    edges {
      node {
        node {
          ips {
            address
          }
        }
      }
    }
  }
}

fragment AssetPageDomainName on DomainName {
  domain_name
  ips {
    address
  }
}
