export interface Issue {
  name: string;
  severity: string;
  status: string;
  affected_entity: string;
  description: string
}

export const issues: Array<Issue> = [
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
  },
]
