export interface Issue {
  name: string;
  severity: string;
  status: string;
  affected_entity: string;
  description: string;
  last_seen: string
}

export const issues: Array<Issue> = [
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '06/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.204.182:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '07/08/2024',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
    last_seen: '07/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.22:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '08/08/2024',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.144',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
    last_seen: '09/08/2024',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.221',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.', 
    last_seen: '09/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.19:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '09/08/2024',
 },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.220',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.', 
    last_seen: '10/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.22:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '09/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.187.229:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '12/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.88.102:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '13/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.94.10:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '12/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.88.63:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '13/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.88.100:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '13/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.80:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '15/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.144:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '13/08/2024',
  },
  {
    name: 'Exposed FTP Service',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.88.61:21/tcp',
    description: 'An exposed FTP service was found on the host',
    last_seen: '14/08/2024',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.2',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
    last_seen: '16/08/2024',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.146',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
    last_seen: '16/08/2024',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.204.215',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
    last_seen: '17/08/2024',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.146',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
    last_seen: '17/08/2024',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.30.80',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
    last_seen: '18/08/2024',
  },
  {
    name: 'CVE-2020-12063',
    severity: 'medium',
    status: 'open',
    affected_entity: '193.1.94.10',
    description: 'A certain Postfix 2.10.1-7 package could allow an attacker to send an email from an arbitrary-looking sender via a homoglyph attack, as demonstrated by the similarity of \xce\xbf to the o character.',
    last_seen: '18/08/2024',
  },
]
